name: flutter_state_management_example
description: Demonstrates how to use the flutter_state_management plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_state_management:
    path: ../

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
