name: flutter_state_management
description: A new Flutter package project.
version: 2.0.0
repository: https://github.com/albemala/flutter_state_management

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

  very_good_analysis: ^5.0.0+1
